// ES6 module syntax
import { I18n } from 'i18n-js';

let strings = new I18n({
  en: {
    you: 'You',
    daily: 'Daily',
    divine: 'Cosmic Plan',
    chat: 'Chat',
    shop: 'Shop',
    introHome:
      "Hi. I’m Luna <3 I'm your friendly neighborhood astro-guru 🌟🔮 Time to unravel the celestial gossip about YOU, darling! ",
    elementDist: 'Elemental Distribution',
    quantityDist: 'Quality Distribution',
    planetSignDist: 'Planets and Signs',
    Earth: 'Earth',
    Fire: 'Fire',
    Water: 'Water',
    Air: 'Air',
    Mutable: 'Mutable',
    Fixed: 'Fixed',
    Cardinal: 'Cardinal',
    Sun: 'Sun',
    Virgo: 'Virgo',
    loading: 'Be patient my friend 😗',
    divineLuna:
      'Luna the Cosmic Oracle is all ears and ready to spill some celestial tea! 🍵🔮',
    self: 'SELF',
    mood: 'MOOD',
    love: 'LOVE',
    career: 'CAREER',
    others: 'Your own question',
    chatLuna: 'What secrets of the universe are you dying to uncover today?',
    writeAMessage: 'Write a message',
    shopLuna:
      "🌟✨ Ready to uncover cosmic secrets with Luna? We'll take a peek at what  Chiêm Tinh Số and AstroBot have in our celestial toolbox.",
    shopTitle: 'Decoding Fate with Astrology',
    shopContent:
      'Decode your destiny with an astrological chart to help you understand yourself and live more fully.',
    shopTitle2: 'Personal Love Discovery',
    shopContent2:
      'Discovering your personal love destiny to know who you will love, when you are likely to fall in love and marry, and what the ups and downs of love will be.',
    shopTitle3: 'Unlocking Career Potential',
    shopContent3:
      'Discover your potential with an astrological chart to help you orient your career effectively.',
    updateAppLangSuccess: "Update App's Language successfully!",
    updateSuccess: 'Update successfully!',
    settings: 'Settings',
    appLang: "App's Language",
    contentLang: "Content's Language",
    lang: 'Language',
    profile: 'Profile',
    termOfService: 'Terms of Service',
    termOfPrivacy: 'Term of Privacy',
    hi: 'Hi!',
    logout: 'Are you sure you want to Logout Account?',
    updatePicture: 'Update Profile Picture',
    save: 'Save',
    uploadFromGallery: 'Upload from Gallery',
    uploadFromCamera: 'Upload from Camera',
    nameOrNickName: 'Name/Nickname',
    birthday: 'Birthdate',
    timeOfBirth: 'Time of Birth',
    placeOfBirth: 'Place of Birth',
    gender: 'Gender',
    relationship: 'Relationship Status',
    txtLogout: 'Logout',
    cancel: 'Cancel',
    agree: 'Agree',
    atroEvent: 'Astrology Events',
    pros: 'Positive Traits',
    cons: 'Negative Traits',
    favorite: 'Likes',
    daily_emotion: 'Emotion',
    daily_love: 'Love',
    daily_career: 'Career',
    daily_money: 'Money',
    daily_heath: 'Health',
    text_choose_language: 'Please choose your language',
    txt_choose_a_lang: 'Choose a language',
    continue: 'Continue',
    city_state_nation: 'City, State, Nation',
    relationship_state: 'Relationship  Status',
    continueGoogle: 'Continue with Google',
    continueApple: 'Continue with Apple',
    continueFacebook: 'Continue with Facebook',
    bycontinue: "By continuing, you agree to AstroBot's ",
    acknowledge: ' and acknowledge our ',
    textVietName: 'Vietnamese',
    txtEnglish: 'English',
    txtDone: 'Done',
    timezone: 'Timezone',
    chooseTimezone: 'Choose Timezone',
    inputTimezone: 'Input timezone search...',
    weareall: 'We are all stardust...',
    txtDeleteAccount: 'Delete Account',
    txtConfirmDeleteAccount: 'Are you sure you want to delete your account?',
    singleAndLookingForLove: 'Single and looking for love',
    singleAndHappyWithIt: 'Single and totally happy with it',
    inRelationship: 'In a relationship',
    female: 'Female',
    male: 'Male',
    other: 'Other',
    dominantElement: 'Dominant Element',
    dominantQuantity: 'Dominant Quantity',
    requestLocation:
      'Your current location is used to enable app features and is not shared with third parties',
    requestLib:
      'Images uploaded to the app are solely for display purposes within the app and will not be shared with third parties',
    linkFacebook: "Follow Us on Facebook",
    starMates: 'View your astrological interpretation\nand that of the person you care about',
    choosePersonToView: 'Choose the person you want to view',
    orViewForOthers: 'Or view for others',
    iAm: 'I am:',
    done: 'Done',
    selectHere: 'Select here',
    updateInfo: 'Update\nPersonal Information!',
    hello: 'Hello',
    dailyScreen: 'Daily Screen',
    should: 'Should',
    dont: 'Don\'t',
    personal: 'Personal',
    manifest: 'Manifest',
    manifestMessage: 'What are you waiting for? Listen to the cosmic message and manifest your dreams!',
    futureOfYou: 'Future of you',
    futureOfYouMessage: 'how',
    luckyDay: 'Find lucky Day',
    luckyDayMessage: 'of you',
    week: 'Week',
    month: 'Month',
    pleaseFillInYourInformation: 'Please fill in your information!',
    updateInfoSuccess: 'Update information successfully!',
    requestLang: "Please choose both language and content",
    chooseBirthday: "Choose birthday",
    updateInfoSuccessAvatar: "Update avatar successfully!",
    dayMonthYear: "Day/Month/Year*",
    or: "Or",
    hoursMinutes: "Hours:  00, Minutes: 00",
    hours: "Hours",
    minutes: "Minutes",
    loadingAnswer: "Loading answer...",
    recommendation:"Hello {name}, Do you have any plans coming up? Let the stars reveal what awaits you! 😉"
  },
  vi: {
    chooseBirthday: "Chọn ngày sinh",
    reqestLang: "Vui lòng chọn cả ngôn ngữ và nội dung.",
    manifestMessage: 'Bạn đang mong đợi điều gì? Lắng nghe thông điệp vũ trụ và manifest ước mơ của bạn!',
    personal: 'Cá nhân',
    should: 'Nên',
    dont: 'Không nên',
    hello: 'Xin chào',
    dailyScreen: 'Màn hình hàng ngày',
    updateInfo: 'Cập nhật\nThông tin cá nhân!',
    selectHere: 'Chọn ở đây',
    nameOrNickName: 'Tên/Biệt danh',
    gender: 'Giới tính',
    relationship: 'Tình trạng mối quan hệ',
    iAm: 'Tôi là:',
    done: 'Xong rồi',
    orViewForOthers: 'Hoặc xem cho người khác nữa!',
    choosePersonToView: 'Chọn người bạn muốn xem',
    starMates: 'Xem diễn giải chiêm tinh của bạn\nvà người bạn quan tâm',
    daily_heath: 'Sức khỏe',
    you: 'Cá Nhân',
    daily: 'Hàng ngày',
    divine: 'Cosmic Plan',
    chat: 'Trò chuyện',
    shop: 'Cửa hàng',
    introHome:
      'Xin chào, Luna đây 🌟🔮 Bạn có biết, các chòm sao có thể tiết lộ rất nhiều về bản thân bạn không? Thử khám phá cùng Luna nhé <3',
    elementDist: 'Phân bố Nguyên tố',
    quantityDist: 'Phân bố Tính chất',
    planetSignDist: 'Hành tinh và cung hoàng đạo',
    Earth: 'Đất',
    Fire: 'Lửa',
    Water: 'Nước',
    Air: 'Khí',
    Mutable: 'Tiên phong',
    Fixed: 'Kiên định',
    Cardinal: 'Linh hoạt',
    Sun: 'Mặt trời',
    Virgo: 'Xử nữ',
    loading: 'Chờ Luna một chút nha',
    divineLuna:
      'Tiên tri siêu cấp vũ trụ Luna đã sẵn sàng xem quẻ cho bạn rồi đây 😗',
    self: 'Bản thân',
    mood: 'Cảm xúc',
    love: 'Tình yêu',
    career: 'Sự nghiệp',
    others: 'câu hỏi khác',
    chatLuna: 'Bạn muốn tâm sự với Luna hôm nay? 😗',
    writeAMessage: 'Gửi tin nhắn',
    shopLuna:
      'Luna xin giới thiệu các sản phẩm giải mã chi tiết dựa trên bản đồ sao cá nhân của Chiêm Tinh Số và AstroBot <3 Hãy khám phá xem các chòm sao bật mí gì về bạn nè!',
    shopTitle: 'Giải mã số phận với Bản đồ sao',
    shopContent:
      'Giải mã số phận với bản đồ sao giúp bạn hiểu rõ bản thân và sống trọn vẹn hơn.',
    shopTitle2: 'Khám phá tình duyên cá nhân',
    shopContent2:
      'Khám phá nhân duyên của cá nhân bạn sẽ giúp bạn biết được bạn sẽ yêu người thế nào, có khả năng yêu và kết hôn khi nào, có những thăng trầm thế nào trong chuyện tình cảm.',
    shopTitle3: 'Mở khóa sự nghiệp',
    shopContent3:
      'Mở khóa sự nghiệp giúp bạn khám phá bản thân và định hướng nghề nghiệp hiệu quả.',
    updateAppLangSuccess: 'Cập nhật ngôn ngữ ứng dụng thành công!',
    updateSuccess: 'Cập nhật thành công',
    settings: 'Cài đặt',
    appLang: 'Ngôn ngữ của Ứng dụng',
    contentLang: 'Ngôn ngữ của Nội dung',
    lang: 'Ngôn ngữ',
    profile: 'Hồ sơ cá nhân',
    termOfService: 'Điều khoản dịch vụ',
    termOfPrivacy: 'Điều khoản bảo mật',
    hi: 'Chào bạn!',
    logout: 'Bạn chắc chắn muốn thoát ứng dụng?',
    updatePicture: 'Cập nhật ảnh đại diện',
    save: 'Lưu chỉnh sửa',
    uploadFromGallery: 'Tải lên từ thư viện',
    uploadFromCamera: 'Tải lên từ Camera',
    birthday: 'Ngày sinh',
    timeOfBirth: 'Giờ sinh',
    placeOfBirth: 'Nơi sinh',
    txtLogout: 'Đăng xuất',
    cancel: 'Huỷ',
    agree: 'Đồng ý',
    atroEvent: 'Sự kiện chiêm tinh',
    pros: 'Xu hướng tích cực',
    cons: 'Xu hướng tiêu cực',
    favorite: 'Ưa thích',
    daily_emotion: 'Cảm xúc',
    daily_love: 'Tình yêu',
    daily_career: 'Sự nghiệp',
    daily_money: 'Tiền bạc',
    text_choose_language: 'Vui lòng chọn ngôn ngữ',
    txt_choose_a_lang: 'Chọn ngôn ngữ',
    continue: 'Tiếp tục',
    city_state_nation: 'Tỉnh/ Thành phố, Quốc gia',
    relationship_state: 'Tình trạng mối quan hệ',
    continueGoogle: 'Tiếp tục với Google',
    continueApple: 'Tiếp tục với Apple',
    continueFacebook: 'Tiếp tục với Facebook',
    bycontinue: 'Bằng cách tiếp tục, bạn đồng ý với AstroBot ',
    acknowledge: ' và ',
    textVietName: 'Tiếng việt',
    txtEnglish: 'Tiếng anh',
    txtDone: 'Xong',
    timezone: 'Múi giờ',
    chooseTimezone: 'Chọn múi giờ',
    inputTimezone: 'Nhập múi giờ tìm kiếm...',
    weareall: 'Chúng ta đều sinh ra từ những bụi sao',
    txtDeleteAccount: 'Xóa tài khoản',
    txtConfirmDeleteAccount: 'Bạn chắc chắn muốn xoá tài khoản?',
    singleAndLookingForLove: 'Độc thân và đang tìm kiếm tình yêu',
    singleAndHappyWithIt: 'Độc thân và hoàn toàn thích thế',
    inRelationship: 'Trong một mối quan hệ',
    female: 'Nữ',
    male: 'Nam',
    other: 'Khác',
    dominantElement: 'Nguyên tố trội',
    dominantQuantity: 'Tính chất trội',
    requestLocation:
      'Địa điểm hiện tại của bạn được sử dụng để thực hiện tính năng của ứng dụng và sẽ không được chia sẻ cho bên thứ ba',
    requestLib:
      'Hình ảnh tải lên ứng dụng chỉ được sử dụng để hiển thị trên ứng dụng và sẽ không được chia sẻ cho bên thứ ba',
    linkFacebook: "Theo dõi chúng tôi trên Facebook",
    futureOfYou: 'Tương lai của bạn',
    futureOfYouMessage: ' thế nào',
    luckyDay: 'Tìm ngày may mắn',
    luckyDayMessage: 'của bạn',
    week: 'Tuần này',
    month: 'Tháng này',
    pleaseFillInYourInformation: 'Vui lòng điền thông tin của bạn!',
    updateInfoSuccess: 'Cập nhật thông tin thành công!',
    updateInfoSuccessAvatar: "Cập nhật ảnh đại diện thành công!",
    dayMonthYear: "Ngày/Tháng/Năm*",
    or: "Hoặc",
    hoursMinutes: "Giờ:  00, Phút: 00",
    hours: "Giờ",
    minutes: "Phút",
    loadingAnswer: "Đang tải câu trả lời...",
    recommendation: "Chào {name}, Bạn có dự định gì sắp tới không? Hãy để các vì sao tiết lộ điều gì đang chờ đón bạn! 😉"
  },
});
strings.enableFallback = true;
strings.defaultLocale = 'en';
strings.locale = 'en';

export default strings;
